# Generated by Django 4.1.6 on 2023-05-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='preProcessedImages',
        ),
    ]
